<a href="https://colab.research.google.com/github/jbvrstg/linealgebra/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Linear ALgebra for ECE


###Laboratory 4 : Matrices

Now that you have fundamental knowledge about Python, we'll try to look into greater dimensions.

###Objectives

At the end of this activity you will be able to:


1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.
3.    Program and translate matrix equations and operations using Python.



###Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

$$
A = \left\{
    \begin{array}\
        x_1 + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
A = np.array([
      [1, 2],
      [3, 10]        
])
describe_mat(A)

Matrix:
[[ 1  2]
 [ 3 10]]

Shape:	(2, 2)
Rank:	2



In [ ]:
B = np.array([[
      [8, 2],
      [5, 4],
      [7, 7]        
]])
describe_mat(B)

Matrix:
[[[8 2]
  [5 4]
  [7 7]]]

Shape:	(1, 3, 2)
Rank:	3



In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
     [1,2,5],
     [3,3,8]                       
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square:True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square:False



###Null Matrix

In [ ]:
def describe_mat(matrix):
  if matrix.size < 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')
  else:
    print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


###Zero Matrix

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'zero Row Matrix: \n{zero_mat_row}')
print(f'zero Row Matrix: \n{zero_mat_sqr}')
print(f'zero Row Matrix: \n{zero_mat_rct}')

zero Row Matrix: 
[[0. 0.]]
zero Row Matrix: 
[[0. 0.]
 [0. 0.]]
zero Row Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


###Ones Matrix

In [ ]:
zero_mat_row = np.ones((1,2))
zero_mat_sqr = np.ones((2,2))
zero_mat_rct = np.ones((3,2))

print(f'zero Row Matrix: \n{zero_mat_row}')
print(f'zero Row Matrix: \n{zero_mat_sqr}')
print(f'zero Row Matrix: \n{zero_mat_rct}')

zero Row Matrix: 
[[1. 1.]]
zero Row Matrix: 
[[1. 1.]
 [1. 1.]]
zero Row Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix

In [ ]:
np.array([
      [2,0,0],
      [0,3,0],
      [0,0,5]
])


array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

###Identity Matrix

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###Upper Triangular Matrix

In [ ]:
np.array([
      [2,1,3],
      [0,3,1],
      [0,0,5]
])


array([[2, 1, 3],
       [0, 3, 1],
       [0, 0, 5]])

###Lower Triangular Matrix

In [ ]:
np.array([
      [5,0,0],
      [1,3,0],
      [1,2,3]
])

array([[5, 0, 0],
       [1, 3, 0],
       [1, 2, 3]])

###Practice

In [ ]:
np.array([
    [1, 4, -7]
])


array([[ 1,  4, -7]])

$$

*   List item
*   List item


G = \left\{
    \begin{array}\
        x_1 + 7x_2 + 8x_3\\ 
        2x_1 + 2x_2 + 2x_3\\
        4x_1 + 6x_2 + 7_3
    \end{array}
\right.$$

G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}

###Matrix Algebra

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])

B = np.array([
    [2,2],
    [0,0],
    [1,1]          
])

A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [ ]:
2+A 

array([[3, 4],
       [4, 5],
       [6, 3]])

In [ ]:
2*np.ones(A.shape)+A

array([[3., 4.],
       [4., 5.],
       [6., 3.]])

In [ ]:
2*np.ones(A.shape)+A == 2+A 

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [ ]:
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

###Element Wise Multiplacation

In [ ]:
A*B

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [ ]:
A@B

ValueError: ignored

In [ ]:
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5, 1. ],
       [inf, inf],
       [4. , 1. ]])

In [ ]:
alpha = 10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [ ]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

###Activity


###Task 1
Create a function named `desc_mat()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

###Function Area

In [ ]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

###Matrix Declaration

In [ ]:
## Null Matrix
null_mat = np.array([])


In [ ]:
## Zero Matrix
zero_mat_sqr = np.zeros((3,3))

In [ ]:
## Ones Matrix
ones_mat_sqr = np.ones((3,3))

In [ ]:
## Diagonal Matrix
A = np.array([
    [1, 0, 0],
    [0, 8, 0],
    [0, 0, 4]
])

In [ ]:
## Identity Matrix
# np.identity(3)


In [ ]:
## Upper Triangular Matrix
B = np.array([
    [1, 2, 3],
    [0, 6, 4],
    [0, 0, 6]
])

In [ ]:
#Lower Triangular Matrix
C = np.array([
    [1, 0, 0],
    [8, 6, 0],
    [4, 5, 6]
])

###Test Areas

In [ ]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [ ]:
## Zero Matrix
desc_mat(zero_mat_sqr)


Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Diagonal Matrix
desc_mat(A)

Matrix:
[[1 0 0]
 [0 8 0]
 [0 0 4]]

Shape:	(3, 3)
Rank:	2



In [ ]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Upper Triangular Matrix
desc_mat(B)

Matrix:
[[1 2 3]
 [0 6 4]
 [0 0 6]]

Shape:	(3, 3)
Rank:	2



In [ ]:
#Lower Triangular Matrix
desc_mat(C)

Matrix:
[[1 0 0]
 [8 6 0]
 [4 5 6]]

Shape:	(3, 3)
Rank:	2



###Task 2
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.###Task 2

###Function Area

In [ ]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

###Matrix Declaration

In [ ]:
## Addition
A = np.array([
    [1,3,6],
    [1,2,8],
    [3,2,9]
])
B = np.array([
    [1,3,4],
    [3,1,2],
    [6,9,8]
])

In [ ]:
## Subtraction
D = np.array([
    [4,2,3],
    [1,8,6],
    [9,6,0]
])
E = np.array([
    [1,4,5],
    [4,2,6],
    [1,9,8]
])

In [ ]:
## element-wise multiplication
F = np.array([
    [3,1,2],
    [2,4,5],
    [6,9,8]
])
G = np.array([
    [2,3,5],
    [1,4,9],
    [0,3,7]
])

In [ ]:
## element-wise division
H = np.array([
    [11,12,15],
    [13,19,8],
    [22,18,16]
])
I = np.array([
    [1,6,5],
    [3,3,3],
    [7,10,2]
])

###Test Areas

In [ ]:
## Addition
C = A+B
mat_operations(C)

NameError: ignored

In [ ]:
np.add(A,B)

array([[ 2,  6, 10],
       [ 4,  3, 10],
       [ 9, 11, 17]])

In [ ]:
## Subtraction
S = D-E
mat_operations(S)

Matrix:
[[ 3 -2 -2]
 [-3  6  0]
 [ 8 -3 -8]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.subtract(D,E)

array([[ 3, -2, -2],
       [-3,  6,  0],
       [ 8, -3, -8]])

In [ ]:
## element-wise multiplication
M = F*G
mat_operations(M)

NameError: ignored

In [ ]:
np.multiply(F,G)

array([[ 6,  3, 10],
       [ 2, 16, 45],
       [ 0, 27, 56]])

In [ ]:
4*G

array([[ 8, 12, 20],
       [ 4, 16, 36],
       [ 0, 12, 28]])

In [ ]:
## element-wise division
V = H/I
mat_operations(V)

Matrix:
[[11.          2.          3.        ]
 [ 4.33333333  6.33333333  2.66666667]
 [ 3.14285714  1.8         8.        ]]

Shape:	(3, 3)
Rank:	2



In [ ]:
np.divide(H,I)

array([[11.        ,  2.        ,  3.        ],
       [ 4.33333333,  6.33333333,  2.66666667],
       [ 3.14285714,  1.8       ,  8.        ]])

In [ ]:
np.divide(H,I)

array([[11.        ,  2.        ,  3.        ],
       [ 4.33333333,  6.33333333,  2.66666667],
       [ 3.14285714,  1.8       ,  8.        ]])

In [ ]:
H/5

array([[2.2, 2.4, 3. ],
       [2.6, 3.8, 1.6],
       [4.4, 3.6, 3.2]])

In [ ]:
1/I

array([[1.        , 0.16666667, 0.2       ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.14285714, 0.1       , 0.5       ]])

###Conclusion


To conclude, the matrix we are using is beneficial and powerful in mathematics analysis and data collection. Apart from simultaneous equations, the properties of matrices are useful in programming, where we utilize an array, which is a matrix, to store data. A matrix's numbers can be used to represent data or mathematical equations. They're used to approximate more sophisticated calculations quickly. Originally, they were created to describe systems of linear equations. Computers can multiply matrices to solve systems of linear equations in applications like image processing and genetic research. It is helpful for us, ECE students for the future, for us, to be able to lessen the time we consume on one task. In short, it is very helpful to make the work easy.